"""
AI Interactions Repository

Every call to the Gemini service — success or failure — is recorded here.

Document schema (ai_interactions collection)
--------------------------------------------
Field        Type          Notes
-----------  ------------  ------------------------------------------------
_id          ObjectId      Auto-generated by MongoDB
user_id      str           Authenticated user's string ID
feature      str           "chat" | "healthcare" | "agriculture" |
                           "career" | "schemes" | "key_verify"
prompt       str           Full text sent to Gemini
response     str           Response text on success; "" on failure
success      bool          True = Gemini returned a response
                           False = any error (key invalid, quota, safety…)
latency_ms   float         Round-trip wall-clock time in milliseconds
error_type   str | None    GeminiError subclass name on failure; None on success
created_at   datetime      UTC timestamp of the call

API KEY GUARANTEE
-----------------
The GEMINI_API_KEY is configured inside GeminiService._ensure_initialized()
using genai.configure(api_key=...).  It is NOT passed to log_interaction()
and does NOT appear in any field of any document stored here.  The only
fields written are the ones listed above — none of which hold the key.
"""

from datetime import datetime
from typing import Optional, List

from app.db.database import db
from app.core.logger import app_logger


ai_interactions_collection = db["ai_interactions"]

# Exhaustive set of field names written to MongoDB.
# The API key is not in this set — enforced by the schema below.
_DOCUMENT_FIELDS = frozenset({
    "user_id", "feature", "prompt", "response",
    "success", "latency_ms", "error_type", "created_at",
})


# ---------------------------------------------------------------------------
# Index initialization
# ---------------------------------------------------------------------------

async def initialize_ai_interactions_indexes() -> None:
    """Create indexes for the ai_interactions collection."""
    try:
        await ai_interactions_collection.create_index("user_id")
        await ai_interactions_collection.create_index("feature")
        await ai_interactions_collection.create_index([("user_id", 1), ("feature", 1)])
        await ai_interactions_collection.create_index("created_at")
        await ai_interactions_collection.create_index("success")
        app_logger.info("ai_interactions collection indexes created successfully")
    except Exception as exc:
        app_logger.warning(f"ai_interactions index creation skipped or failed: {exc}")


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

async def log_interaction(
    user_id: str,
    feature: str,
    prompt: str,
    response: str,
    success: bool,
    latency_ms: float,
    error_type: Optional[str] = None,
) -> str:
    """
    Persist one Gemini interaction to MongoDB.

    Called by GeminiService.generate() for BOTH successful and failed requests:
      - success=True  : response contains the generated text, error_type=None
      - success=False : response="", error_type=<GeminiError subclass name>

    The GEMINI_API_KEY is never passed to this function and is never stored
    in any field.  The full list of stored fields is exactly _DOCUMENT_FIELDS.

    Returns the inserted document _id as a string, or "" if the insert fails
    (a logging failure must never crash the main request path).
    """
    try:
        doc = {
            "user_id":    user_id,
            "feature":    feature,
            "prompt":     prompt,
            "response":   response,
            "success":    success,
            "latency_ms": latency_ms,
            "error_type": error_type,
            "created_at": datetime.utcnow(),
        }

        # Runtime assertion: catch any future code change that accidentally
        # adds a key-bearing field before it reaches MongoDB.
        assert set(doc.keys()) == _DOCUMENT_FIELDS, (
            f"ai_repository schema drift: {set(doc.keys())} != {_DOCUMENT_FIELDS}"
        )

        result = await ai_interactions_collection.insert_one(doc)
        return str(result.inserted_id)

    except AssertionError:
        # Schema drift is a programming error — re-raise so it surfaces in tests.
        raise
    except Exception as exc:
        # Any other failure (network, Atlas down) must not crash the caller.
        app_logger.warning(f"Failed to log AI interaction to MongoDB: {exc}")
        return ""


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------

async def get_user_interactions(
    user_id: str,
    feature: Optional[str] = None,
    skip: int = 0,
    limit: int = 50,
) -> List[dict]:
    """Return paginated interaction history for a user, optionally filtered by feature."""
    try:
        filt: dict = {"user_id": user_id}
        if feature:
            filt["feature"] = feature
        cursor = (
            ai_interactions_collection
            .find(filt)
            .sort("created_at", -1)
            .skip(skip)
            .limit(limit)
        )
        return await cursor.to_list(length=limit)
    except Exception as exc:
        app_logger.error(f"Error fetching AI interactions for user '{user_id}': {exc}")
        return []


async def count_user_interactions(
    user_id: str,
    feature: Optional[str] = None,
) -> int:
    """Count total AI interactions for a user, optionally filtered by feature."""
    filt: dict = {"user_id": user_id}
    if feature:
        filt["feature"] = feature
    return await ai_interactions_collection.count_documents(filt)
